package datatest

import "net/http"

type testdatas []struct {
	Name     string
	Method   string
	Url      string
	Body     interface{}
	Expected int
}

var Testdata = testdatas{
	{
		Name:     "Delete all",
		Method:   "DELETE",
		Url:      "/delete/all",
		Body:     nil,
		Expected: http.StatusOK,
	},
	{
		Name:     "List No Kitten",
		Method:   "GET",
		Url:      "/list",
		Body:     nil,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Delete all Incorrect Method",
		Method:   "GET",
		Url:      "/delete/all",
		Body:     nil,
		Expected: http.StatusMethodNotAllowed,
	},
	{
		Name:     "List No Kitten Incorrect Method",
		Method:   "POST",
		Url:      "/list",
		Body:     nil,
		Expected: http.StatusMethodNotAllowed,
	},
	{
		Name:     "Insert No Data Sent",
		Method:   "POST",
		Url:      "/insert",
		Body:     nil,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Insert Blank Data Sent",
		Method:   "POST",
		Url:      "/insert",
		Body:     "",
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Insert Bad Data Sent",
		Method:   "POST",
		Url:      "/insert",
		Body:     `{"nae": "Felix", "weight": 12.3}`,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Insert Bad Data Id Sent",
		Method:   "POST",
		Url:      "/insert",
		Body:     `{"Id": 3, "name": "Felix", "weight": 12.3}`,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Insert Correct Data Sent",
		Method:   "POST",
		Url:      "/insert",
		Body:     `{"name": "Felix", "weight": 12.3}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Insert Correct Data Sent",
		Method:   "POST",
		Url:      "/insert",
		Body:     `{"name": "Garfield", "weight": 15.0}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Insert Correct Data Sent Incorrect Method",
		Method:   "GET",
		Url:      "/insert",
		Body:     `{"name": "Fat Freddys Cat", "weight": 20.0}`,
		Expected: http.StatusMethodNotAllowed,
	},
	{
		Name:     "Insert Correct Data Sent",
		Method:   "POST",
		Url:      "/insert",
		Body:     `{"name": "Fat Freddys Cat", "weight": 20.0}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "List Kitten Exist",
		Method:   "GET",
		Url:      "/list",
		Body:     nil,
		Expected: http.StatusOK,
	},
	{
		Name:     "Search Name No Name Sent",
		Method:   "GET",
		Url:      "/search/name",
		Body:     nil,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Search Name Blank Name Is Sent",
		Method:   "GET",
		Url:      "/search/name",
		Body:     "",
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Search Name Bad Data Sent",
		Method:   "GET",
		Url:      "/search/name",
		Body:     `{"nme":"Garfield"}`,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Search Name Not Found",
		Method:   "GET",
		Url:      "/search/name",
		Body:     `{"name":"Guarimba"}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Search Name Found",
		Method:   "GET",
		Url:      "/search/name",
		Body:     `{"name":"Garfield"}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Search Id No Id Sent",
		Method:   "GET",
		Url:      "/search/id",
		Body:     nil,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Search Id Blank Id Is Sent",
		Method:   "GET",
		Url:      "/search/id",
		Body:     "",
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Search Id Bad Data Sent",
		Method:   "GET",
		Url:      "/search/name",
		Body:     `{"d": 1}`,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Search Id Not Found",
		Method:   "GET",
		Url:      "/search/id",
		Body:     `{"id": 20}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Search Id Found",
		Method:   "GET",
		Url:      "/search/id",
		Body:     `{"id": 2}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Delete Name No Name Sent",
		Method:   "DELETE",
		Url:      "/delete/name",
		Body:     nil,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Delete Name Blank Name Is Sent",
		Method:   "DELETE",
		Url:      "/delete/name",
		Body:     "",
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Delete Name Bad Data Sent",
		Method:   "DELETE",
		Url:      "/delete/name",
		Body:     `{"nme":"Garfield"}`,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Delete Name Not Found",
		Method:   "DELETE",
		Url:      "/delete/name",
		Body:     `{"name":"Guarimba"}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Delete Name Found",
		Method:   "DELETE",
		Url:      "/delete/name",
		Body:     `{"name":"Garfield"}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Search Name Not Found",
		Method:   "GET",
		Url:      "/search/name",
		Body:     `{"name":"Garfield"}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Search Id Not Found",
		Method:   "GET",
		Url:      "/search/id",
		Body:     `{"id": 2}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Delete Id No Id Sent",
		Method:   "DELETE",
		Url:      "/delete/id",
		Body:     nil,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Delete Id Blank Id Is Sent",
		Method:   "DELETE",
		Url:      "/delete/id",
		Body:     "",
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Delete Id Bad Data Sent",
		Method:   "DELETE",
		Url:      "/delete/id",
		Body:     `{"d": 1}`,
		Expected: http.StatusBadRequest,
	},
	{
		Name:     "Delete Id Not Found",
		Method:   "DELETE",
		Url:      "/delete/id",
		Body:     `{"id": 20}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Delete Id Found",
		Method:   "DELETE",
		Url:      "/delete/id",
		Body:     `{"id": 1}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Search Name Not Found",
		Method:   "GET",
		Url:      "/search/name",
		Body:     `{"name":"Felix"}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Search Id Not Found",
		Method:   "GET",
		Url:      "/search/id",
		Body:     `{"id": 1}`,
		Expected: http.StatusNotFound,
	},
	{
		Name:     "Search Name Found",
		Method:   "GET",
		Url:      "/search/name",
		Body:     `{"name":"Fat Freddys Cat"}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Search Id Found",
		Method:   "GET",
		Url:      "/search/id",
		Body:     `{"id": 3}`,
		Expected: http.StatusOK,
	},
	{
		Name:     "Delete all",
		Method:   "DELETE",
		Url:      "/delete/all",
		Body:     nil,
		Expected: http.StatusOK,
	},
	{
		Name:     "List No Kitten",
		Method:   "GET",
		Url:      "/list",
		Body:     nil,
		Expected: http.StatusNotFound,
	},
}
